export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const REGISTRATION_USER_REQUEST = 'REGISTRATION_USER_REQUEST'
export const REGISTRATION_USER_ERROR = 'REGISTRATION_USER_ERROR'
export const REGISTRATION_USER_SUCCESS = 'REGISTRATION_USER_SUCCESS'

export const CHANGE_USER_NAME_REQUEST = 'CHANGE_USER_NAME_REQUEST'
export const CHANGE_USER_NAME_ERROR = 'CHANGE_USER_NAME_ERROR'
export const CHANGE_USER_NAME_SUCCESS = 'CHANGE_USER_NAME_SUCCESS'

export const CHANGE_DESCRIPTION_REQUEST = 'CHANGE_DESCRIPTION_REQUEST'
export const CHANGE_DESCRIPTION_ERROR = 'CHANGE_DESCRIPTION_ERROR'
export const CHANGE_DESCRIPTION_SUCCESS = 'CHANGE_DESCRIPTION_SUCCESS'

export const CHANGE_PHOTO_REQUEST = 'CHANGE_PHOTO_REQUEST'
export const CHANGE_PHOTO_ERROR = 'CHANGE_PHOTO_ERROR'
export const CHANGE_PHOTO_SUCCESS = 'CHANGE_PHOTO_SUCCESS'

export const SET_PHOTO_REQUEST = 'SET_PHOTO_REQUEST'
export const SET_PHOTO_ERROR = 'SET_PHOTO_ERROR'
export const SET_PHOTO_SUCCESS = 'SET_PHOTO_SUCCESS'